// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-kLHOipGmZu7tRZrbnGBSva2gxUi6z6k',
    appId: '1:60930585947:web:ee50e3b37c18a71f09967e',
    messagingSenderId: '60930585947',
    projectId: 'reddit-54e7a',
    authDomain: 'reddit-54e7a.firebaseapp.com',
    storageBucket: 'reddit-54e7a.firebasestorage.app',
    measurementId: 'G-75R4QC0JWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydTYTBjVg9c5GcgX5yOTNfow7fujNWqo',
    appId: '1:60930585947:android:7ba2678c46e8873b09967e',
    messagingSenderId: '60930585947',
    projectId: 'reddit-54e7a',
    storageBucket: 'reddit-54e7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJMDdmkBvZfr6K_q_I9_-LkNK_kXcQ8Hg',
    appId: '1:60930585947:ios:0502f8c88974de1409967e',
    messagingSenderId: '60930585947',
    projectId: 'reddit-54e7a',
    storageBucket: 'reddit-54e7a.firebasestorage.app',
    iosBundleId: 'com.example.reddit',
  );
}
